<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-EFM8U59U" failures="4" tests="9" name="Test" time="79.64" errors="0" timestamp="14 Sep 2021 13:53:07 GMT">
  <testcase classname="com.orangehrm.testcases.TC_Add_Nationality" name="Add_N" time="11.368"/>
  <testcase classname="com.orangehrm.testcases.LoginPageTest" name="verifyLogo" time="0.087"/>
  <testcase classname="com.orangehrm.testcases.LoginPageTest" name="loginTest" time="4.087"/>
  <testcase classname="com.orangehrm.testcases.HomePageTest" name="adminTabTest" time="8.911"/>
  <testcase classname="com.orangehrm.testcases.DataDrivenTest" name="loginTest1" time="3.527"/>
  <testcase classname="com.orangehrm.testcases.DataDrivenTest" name="loginTest1" time="1.342">
    <failure type="java.lang.AssertionError" message="Both the url&amp;apos;s did not match, so test failed expected [http://localhost/orangehrm/symfony/web/index.php/dashboard] but found [http://localhost/orangehrm/symfony/web/index.php/auth/validateCredentials]">
      <![CDATA[java.lang.AssertionError: Both the url's did not match, so test failed expected [http://localhost/orangehrm/symfony/web/index.php/dashboard] but found [http://localhost/orangehrm/symfony/web/index.php/auth/validateCredentials]
at com.orangehrm.testcases.DataDrivenTest.loginTest1(DataDrivenTest.java:21)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- loginTest1 -->
  <testcase classname="com.orangehrm.testcases.DataDrivenTest" name="loginTest1" time="1.966">
    <failure type="java.lang.AssertionError" message="Both the url&amp;apos;s did not match, so test failed expected [http://localhost/orangehrm/symfony/web/index.php/dashboard] but found [http://localhost/orangehrm/symfony/web/index.php/auth/validateCredentials]">
      <![CDATA[java.lang.AssertionError: Both the url's did not match, so test failed expected [http://localhost/orangehrm/symfony/web/index.php/dashboard] but found [http://localhost/orangehrm/symfony/web/index.php/auth/validateCredentials]
at com.orangehrm.testcases.DataDrivenTest.loginTest1(DataDrivenTest.java:21)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- loginTest1 -->
  <testcase classname="com.orangehrm.testcases.DataDrivenTest" name="loginTest1" time="1.215">
    <failure type="java.lang.AssertionError" message="Both the url&amp;apos;s did not match, so test failed expected [http://localhost/orangehrm/symfony/web/index.php/dashboard] but found [http://localhost/orangehrm/symfony/web/index.php/auth/validateCredentials]">
      <![CDATA[java.lang.AssertionError: Both the url's did not match, so test failed expected [http://localhost/orangehrm/symfony/web/index.php/dashboard] but found [http://localhost/orangehrm/symfony/web/index.php/auth/validateCredentials]
at com.orangehrm.testcases.DataDrivenTest.loginTest1(DataDrivenTest.java:21)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- loginTest1 -->
  <testcase classname="com.orangehrm.testcases.DataDrivenTest" name="loginTest1" time="0.383">
    <failure type="java.lang.AssertionError" message="Both the url&amp;apos;s did not match, so test failed expected [http://localhost/orangehrm/symfony/web/index.php/dashboard] but found [http://localhost/orangehrm/symfony/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: Both the url's did not match, so test failed expected [http://localhost/orangehrm/symfony/web/index.php/dashboard] but found [http://localhost/orangehrm/symfony/web/index.php/auth/login]
at com.orangehrm.testcases.DataDrivenTest.loginTest1(DataDrivenTest.java:21)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- loginTest1 -->
</testsuite> <!-- Test -->
